# --- Config "Ricer" Fuzzel ---
font=JetBrainsMono Nerd Font:weight=bold:size=13
icon-theme=Papirus-Dark
icons-enabled=yes
hide-before-typing=no
fields=name,generic,comment,categories,filename
password-character=*
filter-regex-icase=yes

# Géométrie : on le centre mais on le rend élégant
[main]
terminal=kitty
prompt="󰍉 "
placeholder="Search Apps..."
lines=8
horizontal-pad=25
vertical-pad=20
inner-pad=10
line-height=25
letter-spacing=0

[colors]
# Format: RRGGBBAA (Le 'e6' ou 'cc' à la fin gère la transparence)
background=1e1e2ecc
text=cdd6f4ff
prompt=bac2deff
placeholder=7f849cff
input=cdd6f4ff
match=f5c2e7ff
selection=585b70ff
selection-text=f5c2e7ff
selection-match=f5c2e7ff
border=b4befeff

[border]
width=3
radius=50

[dmenu]
exit-immediately-if-empty=yes