## This file is not in use since I use mpvpaper for my wallpaper.

preload = /home/mleroy/Images/wallpapers/wallhaven_2.png
wallpaper = ,/home/mleroy/Images/wallpapers/wallhaven_2.png
splash = false

